language: bash
cache:
  directories:
  - ${HOME}/.ivy2
  - ${HOME}/.m2
  - ${HOME}/.sbt
services: docker
addons:
  apt:
    packages:
    - make
env:
  global:
  - TERRAFORM_VERSION=0.9.6
  - AWSCLI_VERSION=1.11.*
  - DOCKER_COMPOSE_VERSION=1.13.*
  - GT_SITE_SETTINGS_BUCKET=geotrellis-site-production-config-us-east-1
  - AWS_DEFAULT_REGION=us-east-1
  - secure: N1+4QYVCS0PfaUQiMYjFKpvXPZT/fzyHDLCV6yJDPAklkqQ1S6WeVjwDCd9+2IJy4wGKVSzsmf5DFpFutg+JKgiCVfVyr8bXnuqOcZzahGWqD5nEZc2qieYuhUrWcLtlH7TH8Cr+XF0syMJWneVfIvcDQqtvinGgJyyQdNkD4fo=
  - secure: cDXxwiRVgWsipUMM+jKiR1zJBv8hJ/t+SU7Vln317Ehn03Lu3EzkEkftwopIc0YvtdETbTfw4ELt1Uua88tQnkR0fjhY1lljjmCkSJqTgIgqi73aznsmAz9BvfOkXYIISPwFOJ2fJYDL7ToyACPR0kJ79pxYAHQUlhcY/MGtbPs=
  - secure: a5+FAF8HSdAY/1bAsEynlL8W9S9g42GG5rPHNnz3Yzme5SSnYAILPAu0zLqZkGoJmmSX6ZXTvIa1wZuskZeik62WRBMuWjuxshQsNonByDfqCzMI49AwV/i8IdpDLA8ic6BzDFQ0bYGWVka3/WU4ByqlMF5Tn3jxuFX6Z10tuwE=
script:
- mkdir -p ~/.local/bin
- export PATH="~/.local/bin:$PATH"
- pip install --user docker-compose==${DOCKER_COMPOSE_VERSION}
- scripts/cibuild
before_deploy:
- wget -O terraform-${TERRAFORM_VERSION}.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
- unzip -d ~/.local/bin terraform-${TERRAFORM_VERSION}.zip
- pip install --user awscli==${AWSCLI_VERSION}
- rm terraform-${TERRAFORM_VERSION}.zip
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy
  on:
    branch: master
after_deploy:
- rm deployment/terraform/${GT_SITE_SETTINGS_BUCKET}.{tfvars,tfplan}
