# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geotrellis | Fast Raster Processing
description: > # this means to ignore newlines until "baseurl:"
  GeoTrellis is a Scala library and framework that uses Spark to work with
  raster data. It is released under the Apache 2 License. It provides
  raster processing at web speeds (sub-second or less) with RESTful endpoints
  as well as fast batch processing of large raster data sets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://geotrellis.io" # the base hostname & protocol for your site
github_username:  geotrellis

# Build settings
markdown: kramdown

exclude:
  - .gitignore
  - .vagrant/
  - deployment
  - scripts
  - .ruby_version
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Vagrantfile
  - LICENSE
  - netlify.toml
  - README.md
  - node_modules
  