#!/bin/bash

set -e

if [[ -n "${GT_SITE_DEBUG}" ]]; then
    set -x
fi

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Build application for staging or release.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else

        make clean

        echo "Running tests..."
        ./scripts/test

        docker-compose build gtsite-assets

        echo "Building static asset bundle..."
        docker-compose run --rm gtsite-assets
    fi
fi
