#!/bin/bash

set -e

if [[ -n "${GT_SITE_DEBUG}" ]]; then
    set -x
fi

if [[ -n "${TRAVIS_COMMIT}" ]]; then
    VERSION="${TRAVIS_COMMIT:0:7}"
else
    VERSION="$(git rev-parse --short HEAD)"
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Publish images to Amazon ECR
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else

        if [[ -n "${AWS_ECR_ENDPOINT}" ]]; then

            echo "Building geotrellis-service JAR..."
            docker-compose run --rm gtsite-service assembly

            echo "Building gtsite-service and gtsite-nginx containers"
            docker-compose run --rm --entrypoint "/bin/bash -c" gtsite-service \
               "unzip -d /srv/data/hillshade/ -o /srv/data/hillshade/hills.zip"

            VERSION="${VERSION}" \
            docker-compose -f docker-compose.yml \
                           -f docker-compose.test.yml build \
                              gtsite-nginx gtsite-service
            eval "$(aws ecr get-login --no-include-email)"
            docker tag "gtsite-service:${VERSION}" \
                "${AWS_ECR_ENDPOINT}/gtsite-service:${VERSION}"

            docker tag "gtsite-nginx:${VERSION}" \
                "${AWS_ECR_ENDPOINT}/gtsite-nginx:${VERSION}"

            docker push "${AWS_ECR_ENDPOINT}/gtsite-service:${VERSION}"
            docker push "${AWS_ECR_ENDPOINT}/gtsite-nginx:${VERSION}"
        else
            echo "ERROR: No AWS_ECR_ENDPOINT variable defined."
            exit 1
        fi

    fi
fi
