#!/bin/bash

set -e

if [[ -n "${GT_SITE_DEBUG}" ]]; then
    set -x
fi


function usage() {
    echo -n \
"Usage: $(basename "$0")
Starts docker-compose service
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose up gtsite-nginx gtsite-service
    fi
fi
