#!/bin/bash

set -e

if [[ -n "${GT_SITE_DEBUG}" ]]; then
    set -x
fi


function usage() {
    echo -n \
"Usage: $(basename "$0")
Update development environment
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose build gtsite-assets
        docker-compose run --rm gtsite-assets
    fi
fi
